### ISSUE TITLE
Tervehdys

### ISSUE THREAD

**Issue by juhorichard** [Vsimpro/haalarit-bot#1]
Projektistasi saa mainion rungon e2e-testeille, kiitos!
Mikäli sulla on kiinnostusta auttaa enemmän, niin esittelen mielelläni haalaripeliä. 

Parhain terveisin,
Juho

**Comment by Vsimpro** [comment]
Muhun saa yhteyttä esimerkiksi discordin kautta: Vsimpro#4059. 
Jutellaan toki lisää.

-Ville.
